/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialogue: typeof import('./src/components/AboutDialogue.vue')['default']
    AnswersRows: typeof import('./src/components/AnswersRows.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ConversationItemCard: typeof import('./src/components/ConversationItemCard.vue')['default']
    CustomRouter: typeof import('./src/components/CustomRouter.vue')['default']
    EditButton: typeof import('./src/components/EditButton.vue')['default']
    FollowUpDialogue: typeof import('./src/components/FollowUpDialogue.vue')['default']
    FormattedOutput: typeof import('./src/components/FormattedOutput.vue')['default']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    OneRow: typeof import('./src/components/OneRow.vue')['default']
    QuestionInput: typeof import('./src/components/QuestionInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCodeButton: typeof import('./src/components/SelectCodeButton.vue')['default']
  }
}
