/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswersRows: typeof import('./src/components/AnswersRows.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    CodeReviews: typeof import('./src/components/CodeReviews.vue')['default']
    CustomRouter: typeof import('./src/components/CustomRouter.vue')['default']
    FormattedOutput: typeof import('./src/components/FormattedOutput.vue')['default']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    QuestionInput: typeof import('./src/components/QuestionInput.vue')['default']
    QuestionRow: typeof import('./src/components/QuestionRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
